name: Build and Test elevation_mapping

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # build both Release mode
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release ]

    # environment: regular Ubuntu with a vanilla ROS container
    runs-on: ubuntu-latest
    container: 
      image: ros:noetic

    steps:
    - name: Environment Info
      run: |
        pwd
        uname -r
        lsb_release -a
    - name: System deps
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y git libeigen3-dev ninja-build keyboard-configuration
    - uses: actions/checkout@v2
      with: 
        path: src/elevation_mapping 
    - name: Checkout dependencies
      run: |
        git clone https://github.com/anybotics/grid_map src/grid_map
        git clone https://github.com/anybotics/kindr src/kindr
        git clone https://github.com/anybotics/kindr_ros src/kindr_ros
    - name: Rosdep
      run: |
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
    - name: Build (${{ matrix.build_type }})
      shell: bash
      run: |
        source /opt/ros/noetic/setup.bash
        catkin_make_isolated --use-ninja --merge --only-pkg-with-deps elevation_mapping --cmake-args -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} 
        
    - name: Test
      shell: bash
      run: |
        source devel_isolated/setup.bash
        catkin_make_isolated --use-ninja --merge --only-pkg-with-deps elevation_mapping --catkin-make-args run_tests
        catkin_test_results
